FROM node:22-alpine

WORKDIR /app

COPY package.json package-lock.json tsconfig.json ./
COPY apps ./apps
COPY backend ./backend
COPY packages ./packages
COPY services ./services
COPY utilities ./utilities
COPY aws ./aws
COPY frontend ./frontend

RUN npm ci --include=dev

EXPOSE 43872

CMD ["npm", "run", "start", "-w", "@fiapauto/public-api"]
