import fs from 'node:fs/promises'
import path from 'node:path'
import type { JoinedMeeting, RecordingArtifact, RecordingJob } from '../types'
import { ensureDir } from '../utils/fs'

export class LocalRecordingService {
  private readonly recordingsDir: string

  constructor(recordingsDir: string) {
    this.recordingsDir = recordingsDir
  }

  async record(job: RecordingJob, meeting: JoinedMeeting): Promise<RecordingArtifact> {
    await ensureDir(this.recordingsDir)

    const fileName = `${job.lessonId}-${Date.now()}.webm`
    const localPath = path.join(this.recordingsDir, fileName)
    const payload = {
      jobId: job.id,
      lessonId: job.lessonId,
      lessonTitle: job.lessonTitle,
      discipline: job.discipline,
      meetingUrl: meeting.meetingUrl,
      sessionLabel: meeting.sessionLabel,
      capturedAt: new Date().toISOString(),
      note: 'Mock recording artifact generated by the bot skeleton.',
    }

    await fs.writeFile(localPath, JSON.stringify(payload, null, 2), 'utf-8')

    return {
      jobId: job.id,
      lessonId: job.lessonId,
      localPath,
      fileName,
      recordedAt: new Date().toISOString(),
      mimeType: 'video/webm',
    }
  }
}
